In [2]:
#Example:1
inputs=[1.0,2.0,3.0,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2
output=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias)
print(output)

4.8


In [5]:
#Example:1
inputs=[1.0,2.0,3.0,2.5]
#Single output neuron
weights=[0.2,0.8,-0.5,1.0]
bias=2
output=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias)
print(output)

4.8


In [7]:
#4 input neuron and 3 output neuron those are fully connected
#Example2
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]
bias1=2
bias2=3
bias3=0.5
outputs=[
    #Neuron1:
    inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
    #Neuron2:
    inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
    #Neuron3
    inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(outputs)
    


[4.8, 1.21, 2.385]


In [9]:
#input neuron and 3 output neuron those are fully connected
#Example2
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]
bias=[2,3,0.5]
outputs=[
    #For neuron1
    inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias[0],
    #For neuron2
    inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias[1],
    #For neuron3
    inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias[2]]
print(output)


4.8


In [6]:
inputs=[1,2,3,2.5]
weights=[
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]
biases=[2,3,0.5]
#output of the current layer
layer_outputs=[]
#For each neuron
for neuron_weights,neuron_bias in zip(weights,biases):
    #zeroed output of the given neuron
    neuron_output=0
    #For each input and weight to the neuron
    for n_input,weight in zip(inputs,neuron_weights):
         #multiply this input to associated weight
         #and add to the neuron outputs
         neuron_output+=n_input*weight
    #add bias
    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)


[4.8, 1.21, 2.385]


In [9]:
inputs=[1,2,3,2.5]
weights=[
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]
bias=[2,3,0.5]
layer_outputs=[]
for neuron_weights,neuron_bias in zip(weights,bias):
    neuron_output=0
    for each_input,each_weight in zip(inputs,neuron_weights):
        neuron_output+=each_input*each_weight
    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)




[4.8, 1.21, 2.385]


In [11]:
#Example3
inputs=[1,2,3,2.5]
weights=[
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]
layer_outputs=[]
for neuron_bias,neuron_weights in zip(bias,weights):
    neuron_output=0
    for weight,each_input in zip(neuron_weights,inputs):
        neuron_output+=weight*each_input
    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


In [13]:
import numpy as np
inputs=[1.0,2.0,3.0,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2
output=np.dot(inputs,weights)+bias
print(output)

4.8


In [14]:
#Example:4
import numpy
inputs=[1.0,2.0,3.0,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2
output=numpy.dot(inputs,weights)+bias
print(output)

4.8


In [16]:
#complex to easy
import numpy
inputs=[1,2,3,2.5]
weights=[
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]
biases=[2,3,0.5]
outputs=numpy.dot(weights,inputs)+biases
print(outputs)

[4.8   1.21  2.385]


In [20]:
import numpy
inputs=[1,2,3,2.5]
weights=[
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
outputs=(numpy.dot(inputs,numpy.array(weights).T)+biases)
print(outputs)

[4.8   1.21  2.385]


In [21]:
#Example:5
import numpy
inputs=[
    [1.0,2.0,3.0,2.5],
    [2.0,4.0,1.5,2.0],
    [0.5,1.5,2.0,3.5]]
weights=[
    [0.2,0.8,-0.5,1.0],
    [0.5,-0.9,0.3,-0.7],
    [-0.1,0.6,-0.3,0.9]]
biases=[2.0,1.0,-0.5]
output=numpy.dot(inputs,numpy.array(weights).T)+biases
print(output)
    

[[ 4.8  -1.15  1.95]
 [ 6.85 -2.55  3.05]
 [ 5.8  -1.95  2.9 ]]


In [24]:
#Example:6
import numpy
weights=[
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]]
inputs=[
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]]
biases=[2,3,0.5]
weights2=[
    [0.1,-0.14,0.5],
    [-0.5,0.12,-0.33],
    [-0.44,0.73,-0.13]]
biases2=[-1,2,-0.5]
layer1_outputs=np.dot(inputs,np.array(weights).T)+biases
layer2_outputs=np.dot(layer1_outputs,np.array(weights2).T)+biases2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [25]:
import numpy
inputs=[
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]]
weights=[
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
weights2=[
    [0.1,-0.14,0.5],
    [-0.5,0.12,-0.33],
    [-0.44,0.73,-0.13]]
biases2=[-1,2,-0.5]
layer1_outputs=numpy.dot(inputs,numpy.array(weights).T)+biases
layer2_outputs=numpy.dot(layer1_outputs,numpy.array(weights2).T)+biases2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [6]:
#Example:8 Solve AND gate problem using neural network.
import numpy
inputs=numpy.array([[0,0],
                   [0,1],
                   [1,0],
                   [1,1]])
labels=numpy.array([0,0,0,1])
#Define weights and biases
weights=numpy.array([0.5,0.5])
bias=-0.7
#Define the activation function( step function)
def step_function(x):
    if x <= 0:
        return 0
    else:
        return 1
outputs=[]
for input_row in inputs:
    weighted_sum=numpy.dot(input_row,weights)+bias
    output=step_function(weighted_sum)
    outputs.append(output)
print(outputs)
correct_predictions=numpy.sum(outputs==labels)
print("Input: ",inputs)
print("Labels: ",labels)
print("Predicted Outputs: ",outputs)
print("Correct Predictions: ",correct_predictions)
    

                   


[0, 0, 0, 1]
Input:  [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels:  [0 0 0 1]
Predicted Outputs:  [0, 0, 0, 1]
Correct Predictions:  4


In [13]:
#Solve AND gate problem using neural neural network
import numpy
inputs=numpy.array([[0,0],
                    [0,1],
                    [1,0],
                    [1,1]])
labels=numpy.array([0,0,0,1])
weights=numpy.array([-0.5,0.5])
bias=0.8
def step_function(x):
    if x<=0:
        return 0
    else:
        return 1
outputs=[]
for input_row in inputs:
    output=numpy.dot(input_row,weights)+bias
    y=step_function(output)
    outputs.append(y)
correct_prediction=numpy.sum(labels==outputs)
print("Input is: ",inputs)
print("Labels : ",labels)
print("Predicted output is : ",outputs)
print("Correct predictions : ",correct_prediction)

        
    

Input is:  [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels :  [0 0 0 1]
Predicted output is :  [1, 1, 1, 1]
Correct predictions :  1


In [17]:
#Solve AND gate problem using neural network
import numpy
inputs=numpy.array([[0,0],
                    [0,1],
                    [1,0],
                    [1,1]])
labels=numpy.array([0,0,0,1])
weights=numpy.array([0.5,0.5])
bias=-0.7
outputs=[]
def step_function(x):
    if x<=0:
        return 0
    else:
        return 1
for input_row in (inputs):
    output=numpy.dot(input_row,weights)+bias
    y=step_function(output)
    outputs.append(y)
print("Input is: ",inputs)
print("Prediction Output is: ",outputs)
print("Label is : ",labels)
correct_prediction=numpy.sum(labels==outputs)
print("Correct prediction is : ",correct_prediction)


    


Input is:  [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Prediction Output is:  [0, 0, 0, 1]
Label is :  [0 0 0 1]
Correct prediction is :  4


In [18]:
import numpy as np

# use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the neural network architecture
input_size = 2
hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# Forward pass
hidden_layer_output = (np.dot(x, W1) + b1)
output = sigmoid(np.dot(hidden_layer_output, W2) + b2)

# Calculate the loss (using Mean Squared Error)
loss = np.mean((output - target) ** 2)

print("Output:")
print(output)
print("Loss:", loss)


Output:
[[0.30423809]
 [0.52537693]
 [0.41019163]
 [0.63775159]]
Loss: 0.16701570279555805


Example-8

In [7]:
#For 2 inputs and 1 output
import numpy
inputs=numpy.array([[0,0],[0,1],[1,0],[1,1]])
input_size=2
output_size=1
weight_size=2
labels=numpy.array([0,0,0,1])
weights=numpy.random.randn(input_size)
bias=numpy.random.randn(output_size)
def step_function(x):
    return 0 if x<=0 else 1
outputs=[]
for input_row in inputs:
    weighted_sum=numpy.dot(input_row,weights)+bias
    output=step_function(weighted_sum)
    outputs.append(output)
correct_predictions=numpy.sum(outputs==labels)
print("Inputs ",inputs)
print("Labels ",labels)
print("Predicted outputs ",outputs)
print("Correct predictions ",correct_predictions)

Inputs  [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels  [0 0 0 1]
Predicted outputs  [0, 0, 1, 1]
Correct predictions  3


In [2]:
#input size= number of columns
#weight=[output_size][input_size] or [no. of bias][no. of inputs]
#NB:Weight and input er column number same
import numpy
def sigmoid_function(x):
    return 1 / (1 + numpy.exp(-x))

inputs=numpy.random.randn(10,4)
print("\nInput Layer : \n\n",inputs)
input_size=4
hidden_layer1_size=3
hidden_layer2_size=3
output_size=1
weights1=numpy.random.randn(hidden_layer1_size,input_size)
weights2=numpy.random.randn(hidden_layer2_size,hidden_layer1_size)
weights3=numpy.random.randn(output_size,hidden_layer2_size)
print("\nWeights1 :  \n\n",weights1)
print("\nWeights2 : \n\n",weights2)
print("\nWeights3 : \n\n",weights3)
bias1=numpy.random.randn(hidden_layer1_size)
bias2=numpy.random.randn(hidden_layer2_size)
bias3=numpy.random.randn(output_size)
print("\nBias1: \n\n ",bias1)
print("\nBias2: \n\n ",bias2)
print("\nBias3: \n\n ",bias3)
output1=[]
for input_row in inputs:
    weighted_sum = numpy.dot(input_row,numpy.array(weights1).T)+ bias1
    output = sigmoid_function(weighted_sum)
    output1.append(output)
bias2=numpy.array(bias2)
weights2=numpy.array(weights2)
output2=[]
for input_row in output1:
    weighted_sum = numpy.dot(input_row,numpy.array(weights2))+ bias2
    output = sigmoid_function(weighted_sum)
    output2.append(output)
print("\nHidden layer:1 \n\n",numpy.array(output1))
#outputs2=numpy.dot(outputs1,weights2)+bias2
#outputs22=outputs2+numpy.array(bias2).T
print("\nHidden layer:2 \n\n",numpy.array(output2))
output3=[]
for input_row in output2:
    weighted_sum = numpy.dot(input_row,numpy.array(weights3).T)+ bias3
    output = sigmoid_function(weighted_sum)
    output3.append(output)
#outputs3=numpy.dot(outputs2,numpy.array(weights3).T)+bias3
print("\nOutput layer: \n\n",numpy.array(output3))


Input Layer : 

 [[ 1.69601188 -0.75430563 -0.20117845  0.05583929]
 [-0.37757482 -1.30712642  0.70917574  1.2816353 ]
 [ 0.97711491 -0.11906007  0.54768205 -1.83295368]
 [ 0.59335559 -0.35070264 -1.07682443 -0.62141076]
 [-1.45352065 -0.51067737 -0.90200318  0.63946084]
 [-0.09016876  1.80717303 -0.79636695 -0.74873693]
 [-0.11284845  1.35962378  1.7814662  -0.49571487]
 [ 1.86255616  0.0127819   0.78353487  0.80250817]
 [-1.21397236 -1.08422427  0.72124762  0.26101271]
 [-0.84752786 -1.12152946  0.37877261  0.60738374]]

Weights1 :  

 [[-0.6032827  -0.9920629   0.69312423  1.34893599]
 [-1.1635276   0.08642369 -1.36216579 -0.66551581]
 [ 1.48553029  1.24191938 -0.68236026  1.40035828]]

Weights2 : 

 [[ 0.43662989  0.1464421   0.52121749]
 [ 0.7088098  -0.74816857 -0.08764317]
 [-0.18563518 -1.39890512 -1.50204624]]

Weights3 : 

 [[-1.2919672   1.48356538 -1.02321105]]

Bias1: 

  [-0.86489305 -1.62589731 -0.2410489 ]

Bias2: 

  [-0.32230824  0.60568383  0.17788608]

Bias3: 

  [

**With out Activation function with 10 sample inputs**

In [3]:
# input size= number of columns
import numpy
inputs = numpy.random.randn(10, 4)
print("Inputs : \n", inputs)
input_size = 4
hidden_layer1_size = 3
hidden_layer2_size = 3
output_size = 1
weights1 = numpy.random.randn(hidden_layer1_size, input_size)
weights2 = numpy.random.randn(hidden_layer2_size, hidden_layer1_size)
weights3 = numpy.random.randn(output_size, hidden_layer2_size)
print("Weights1 :  \n", weights1)
print("Weights2 : \n", weights2)
print("Weights3 : \n", weights3)
bias1 = numpy.random.randn(hidden_layer1_size)
bias2 = numpy.random.randn(hidden_layer2_size)
bias3 = numpy.random.randn(output_size)
print("Bias1: \n ", bias1)
print("Bias2: \n ", bias2)
print("Bias3: \n ", bias3)
outputs1 = numpy.dot(inputs, numpy.array(weights1).T) + bias1
outputs1 = numpy.array(outputs1)
bias2 = numpy.array(bias2)
weights2 = numpy.array(weights2)
print("Hidden layer:1 \n", outputs1)
outputs2 = numpy.dot(outputs1, weights2) + bias2
# outputs22=outputs2+numpy.array(bias2).T
print("Hidden layer:2 \n", outputs2)
outputs3 = numpy.dot(outputs2, numpy.array(weights3).T) + bias3
print("Output layer: \n", outputs3)


Inputs : 
 [[ 2.27160358  0.27820936  0.91448588  1.11940325]
 [-1.79944085  0.53833516 -1.61222105 -1.09202369]
 [-0.37090378  0.83218316  0.40152181 -0.14937409]
 [ 1.94090769  1.52961737  0.54241028  1.81277479]
 [-0.23712714 -0.45551418 -0.49618307  1.48714353]
 [ 1.356005   -0.2136562   1.87175239 -0.87259052]
 [-0.58395821  0.89404505  0.39420678  0.8557744 ]
 [ 1.71197632  2.11086357  0.80928706  0.42043473]
 [-1.39789373 -1.10398492 -0.93108818  0.49427299]
 [-0.16263086  1.07902567 -0.77104058  1.9771555 ]]
Weights1 :  
 [[-1.16222647e-03  2.37598272e-01 -7.02682143e-02 -1.70208646e+00]
 [ 1.16802662e+00  1.02599884e+00  7.48323921e-01 -2.43217900e-01]
 [-1.57364380e-01 -2.82656671e-01 -8.90672886e-01  6.31721543e-02]]
Weights2 : 
 [[-1.60096832  0.24122019  0.18248374]
 [ 1.37550332 -0.94625839 -0.31519743]
 [-0.52279806  2.32829689  2.34995202]]
Weights3 : 
 [[-0.65060499  0.75952317 -0.3228417 ]]
Bias1: 
  [2.05753896 2.04506716 1.71757803]
Bias2: 
  [-1.0902651  -0.8999518

In [7]:
#Solve AND gate problem using neural network
import numpy
inputs=numpy.array([[0,0],
                    [0,1],
                    [1,0],
                    [1,1]])
labels=numpy.array([0,1,1,1])
weights=numpy.array([1,1])
bias=0.7
def step_function(x):
    if x<=0:
        return 0
    else:
        return 1
outputs=[]
for input_row in inputs:
    output=numpy.dot(input_row,weights)+bias
    y=step_function(output)
    outputs.append(y)
correct_prediction=numpy.sum(labels==outputs)
print("Input is: ",inputs)
print("Labels : ",labels)
print("Predicted output is : ",outputs)
print("Correct predictions : ",correct_prediction)

        
    

Input is:  [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels :  [0 1 1 1]
Predicted output is :  [1, 1, 1, 1]
Correct predictions :  3


In [20]:
import numpy
import pandas
import random
data={
    "Age":numpy.random.randint(20,30,20),
    "Year of experience":numpy.random.randint(2,10,20),
     "salary":numpy.random.randint(35000,40000,20),
}
dataset=pandas.DataFrame(data)
dataset
#dataset['Age']

Age  Year of experience  salary
0    27                   5   36941
1    28                   6   39996
2    26                   9   38696
3    28                   6   38478
4    21                   5   39774
5    24                   6   37840
6    28                   2   38613
7    20                   2   35257
8    20                   4   39180
9    20                   3   35004
10   26                   4   36811
11   25                   5   39243
12   27                   4   37238
13   28                   3   37161
14   26                   4   37850
15   23                   5   39395
16   26                   2   39627
17   21                   2   39066
18   29                   7   39181
19   24                   6   35045

In [26]:
df=pandas.read_csv("co2_country_years_cell_tower_data.csv")
df.head(10)

Country  2014  2020  2020-Population
0                   India  3343   844       1380004385
1                 Nigeria  1745  1900        206139589
2  South & Southeast Asia  1128   926        668619840
3                    MENA  1086  1065        464554123
4      Sub-Saharan Africa   968  1036       1136050000
5           Latin America   408   323        653962331
6                   China   112   490       1439323776
7           Rest of World   454   455       1846144695

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Country          8 non-null      object
 1   2014             8 non-null      int64 
 2   2020             8 non-null      int64 
 3   2020-Population  8 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 388.0+ bytes


In [28]:
df.describe()

2014         2020  2020-Population
count     8.000000     8.000000     8.000000e+00
mean   1155.500000   879.875000     9.743498e+08
std    1022.123839   499.334825     5.622769e+08
min     112.000000   323.000000     2.061396e+08
25%     442.500000   481.250000     6.066103e+08
50%    1027.000000   885.000000     9.023349e+08
75%    1282.250000  1043.250000     1.394834e+09
max    3343.000000  1900.000000     1.846145e+09

In [1]:
import numpy
import pandas
data={"Age":numpy.random.randint(30,40,10),
      "Salary":numpy.random.randint(50000,60000,10),
      "Experience":numpy.random.randint(2,10,10)
     }
dataset=pandas.DataFrame(data)
dataset
      

Age  Salary  Experience
0   34   55288           6
1   30   51967           6
2   36   56308           6
3   34   59521           5
4   39   54346           2
5   32   56276           8
6   34   54517           3
7   39   56393           6
8   35   51759           9
9   34   52933           6