**Exercise: Design the previous examples of neural network by adjusting weights and biases randomly.**

In [2]:
import random
inputs=[1,2,3,2.5]
weights=[]
for i in range(len(inputs)):
    weights.append(random.random())
#print(weights)
bias=random.randint(2,4)
#print(bias)
output_neuron=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias)
print(output_neuron)

5.282857197797338


**Exercise: A fully connected neural network — every neuron in the current layer has connections to every neuron from the previous layer. You have 4 input neurons, one hidden layer consisting of 3 neurons and one output neuron. You should adust weights and biases randomly.**

In [3]:
import random
inputs=[1,2,3,2.5]
weights=[]
rows,cols=3,4
for i in range(rows):
    col=[]
    for k in range(cols):
      col.append(random.random())
    weights.append(col)
hidden_layer=3
bias=[]
for j in range(hidden_layer):
    bias.append(random.randint(-5,5))
print("First layer input weight is: ")
print(weights)
print("Hidden layer neuron bias is: ")
print(bias)
layer_outputs=[]
for neuron_weights,neuron_bias in zip(weights,bias):
    neuron_output=0
    for each_input,each_weight in zip(inputs,neuron_weights):
        neuron_output+=each_input*each_weight
    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)
print("Hidden layer is: ")
print(layer_outputs)
weights2=[]
for i in range(3):
    weights2.append(random.random())
print("Hidden layer neuron weight is: ")
print(weights2)
bias2=random.randint(-5,5)
output_neuron=(layer_outputs[0]*weights2[0]+layer_outputs[1]*weights2[1]+layer_outputs[2]*weights2[2]+bias2)
print("Output neuron is: ") 
print(output_neuron)

First layer input weight is: 
[[0.7762501849081956, 0.6599051399984811, 0.06505014533369402, 0.9024473721905151], [0.7227290112759254, 0.567900416909339, 0.552670176036438, 0.2017164785089619], [0.3290779537583085, 0.13306107106344434, 0.23587603282579261, 0.48393964266392187]]
Hidden layer neuron bias is: 
[5, -5, -4]
Hidden layer is: 
[9.547329331382528, -0.9791684305236776, -1.4873226989776205]
Hidden layer neuron weight is: 
[0.675817626795257, 0.06410321367189986, 0.4402967333869673]
Output neuron is: 
8.734622281992916


**Exercise: take inputs containing 3 samples with 4 features, and 3 neurons with weights and biases, respectively. Then print the outputs of the neorons.**


In [1]:
import numpy
inputs=numpy.array([[1.0, 2.0, 3.0, 2.5],
[2.0, 4.0, 1.5, 2.0],
[0.5, 1.5, 2.0, 3.5]])
weights=numpy.array([[0.2, 0.8, -0.5, 1.0],
                    [0.5, -0.9, 0.3, -0.7],
                    [-0.1, 0.6, -0.3, 0.9]])
bias=numpy.array([2.0,1.0,-0.5])
outputs=numpy.dot(inputs,weights.T)+bias
print(outputs)


[[ 4.8  -1.15  1.95]
 [ 6.85 -2.55  3.05]
 [ 5.8  -1.95  2.9 ]]


**Exercise: take inputs containing 3 samples with 4 features, and 3 neurons with weights and biases, respectively. Then print the outputs of the neorons.**

In [8]:
import numpy
inputs1=[1.0, 2.0, 3.0, 2.5]
inputs2=[2.0, 4.0, 1.5, 2.0]
inputs3=[0.5, 1.5, 2.0, 3.5]
weights=[[0.2, 0.8, -0.5, 1.0],
                    [0.5, -0.9, 0.3, -0.7],
                    [-0.1, 0.6, -0.3, 0.9]]
bias=[2.0,1.0,-0.5]
outputs=[]
sample_outputs=[]
for neuron_bias,neuron_weights in zip(bias,weights):
    neuron_output=0
    for weight,each_input in zip(neuron_weights,inputs1):
        neuron_output+=weight*each_input
    neuron_output+=neuron_bias
    sample_outputs.append(neuron_output)
print("1st input sample output neuron is:")
print(sample_outputs)

outputs.append(sample_outputs)
sample_outputs=[]
for neuron_bias,neuron_weights in zip(bias,weights):
    neuron_output=0
    for weight,each_input in zip(neuron_weights,inputs2):
        neuron_output+=weight*each_input
    neuron_output+=neuron_bias
    sample_outputs.append(neuron_output)
print("2nd input sample output neuron is:")
print(sample_outputs)

outputs.append(sample_outputs)
sample_outputs=[]
for neuron_bias,neuron_weights in zip(bias,weights):
    neuron_output=0
    for weight,each_input in zip(neuron_weights,inputs3):
        neuron_output+=weight*each_input
    neuron_output+=neuron_bias
    sample_outputs.append(neuron_output)
print("3rd input sample output neuron is:")
print(sample_outputs)

outputs.append(sample_outputs)
output=numpy.array(outputs)
print("Final outputs is : ")
print(output)


1st input sample output neuron is:
[4.8, -1.1500000000000004, 1.9500000000000002]
2nd input sample output neuron is:
[6.85, -2.5500000000000003, 3.05]
3rd input sample output neuron is:
[5.800000000000001, -1.9499999999999997, 2.9]
Final outputs is : 
[[ 4.8  -1.15  1.95]
 [ 6.85 -2.55  3.05]
 [ 5.8  -1.95  2.9 ]]


**Exercise: take inputs containing 3 samples with 4 features, and 3 neurons with weights and biases, respectively. Then print the outputs of the neorons.**

In [11]:
import numpy
inputs=[[1.0, 2.0, 3.0, 2.5],
      [2.0, 4.0, 1.5, 2.0],
         [0.5, 1.5, 2.0, 3.5]]
weights=[[0.2, 0.8, -0.5, 1.0],
                    [0.5, -0.9, 0.3, -0.7],
                    [-0.1, 0.6, -0.3, 0.9]]
bias=[2.0,1.0,-0.5]
outputs=[]

for input_sample in inputs:
   sample_outputs=[]
   for neuron_bias,neuron_weights in zip(bias,weights):
       neuron_output=0
       for weight,each_input in zip(neuron_weights,input_sample):
         neuron_output+=weight*each_input
       neuron_output+=neuron_bias
       sample_outputs.append(neuron_output)
   print("sample output  is:")
   print(sample_outputs)
   outputs.append(sample_outputs)
print("           ")
print("Final output is: ",end="\n") 
print(numpy.array(outputs))


sample output  is:
[4.8, -1.1500000000000004, 1.9500000000000002]
sample output  is:
[6.85, -2.5500000000000003, 3.05]
sample output  is:
[5.800000000000001, -1.9499999999999997, 2.9]
           
Final output is: 
[[ 4.8  -1.15  1.95]
 [ 6.85 -2.55  3.05]
 [ 5.8  -1.95  2.9 ]]


**Exercise: Design the previous examples of neural network by adjusting weights and biases randomly.(Using AND gates)**

In [7]:
#For 2 inputs and 1 output
import numpy
inputs=numpy.array([[0,0],[0,1],[1,0],[1,1]])
input_size=2
output_size=1
weight_size=2
labels=numpy.array([0,0,0,1])
weights=numpy.random.randn(input_size)
bias=numpy.random.randn(output_size)
def step_function(x):
    return 0 if x<=0 else 1
outputs=[]
for input_row in inputs:
    weighted_sum=numpy.dot(input_row,weights)+bias
    output=step_function(weighted_sum)
    outputs.append(output)
correct_predictions=numpy.sum(outputs==labels)
print("Inputs ",inputs)
print("Labels ",labels)
print("Random Biases ",bias)
print("Random weights ",weights)
print("Predicted outputs ",outputs)
print("Correct predictions ",correct_predictions)

Inputs  [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Labels  [0 0 0 1]
Random Biases  [-1.14113328]
Random weights  [-2.15036115 -1.8563513 ]
Predicted outputs  [0, 0, 0, 0]
Correct predictions  3


**Exercise having 10 inputs samples with 4 features(without Activation Function)**

In [4]:
import numpy
def sigmoid_function(x):
    return 1 / (1 + numpy.exp(-x))

inputs=numpy.random.randn(10,4)
print("\nInput Layer : \n\n",inputs)
input_size=4
hidden_layer1_size=3
hidden_layer2_size=3
output_size=1
weights1=numpy.random.randn(hidden_layer1_size,input_size)
weights2=numpy.random.randn(hidden_layer2_size,hidden_layer1_size)
weights3=numpy.random.randn(output_size,hidden_layer2_size)
print("\nWeights1 :  \n\n",weights1)
print("\nWeights2 : \n\n",weights2)
print("\nWeights3 : \n\n",weights3)
bias1=numpy.random.randn(hidden_layer1_size)
bias2=numpy.random.randn(hidden_layer2_size)
bias3=numpy.random.randn(output_size)
print("\nBias1: \n\n ",bias1)
print("\nBias2: \n\n ",bias2)
print("\nBias3: \n\n ",bias3)
output1=[]
for input_row in inputs:
    weighted_sum = numpy.dot(input_row,numpy.array(weights1).T)+ bias1
    output = sigmoid_function(weighted_sum)
    output1.append(output)
bias2=numpy.array(bias2)
weights2=numpy.array(weights2)
output2=[]
for input_row in output1:
    weighted_sum = numpy.dot(input_row,numpy.array(weights2))+ bias2
    output = sigmoid_function(weighted_sum)
    output2.append(output)
print("\nHidden layer:1 \n\n",numpy.array(output1))
print("\nHidden layer:2 \n\n",numpy.array(output2))
output3=[]
for input_row in output2:
    weighted_sum = numpy.dot(input_row,numpy.array(weights3).T)+ bias3
    output = sigmoid_function(weighted_sum)
    output3.append(output)
print("\nOutput layer: \n\n",numpy.array(output3))
                           



Input Layer : 

 [[-0.32165951  1.33369145  0.34127757  0.37837265]
 [-1.22878802  0.77137219 -1.24540942 -0.39899901]
 [-0.71256488 -1.21787593 -1.25656446 -0.56398334]
 [-0.25343714 -0.77600908  1.29931678  0.20122557]
 [ 0.33889547  1.27310803 -1.70209653  0.67417201]
 [-0.007058    0.87399007 -0.32070821  0.09338934]
 [-0.72701064 -0.67598497 -1.81077728 -0.67343286]
 [-0.31628949 -0.58966871  2.27133507  0.45722897]
 [ 1.26317293  1.64028411 -0.65087921  0.95204215]
 [-0.90933372 -0.29638723  1.10618283  0.82268802]]

Weights1 :  

 [[ 0.3087094  -1.52041712  2.15695539  0.63807958]
 [ 0.27754603  0.875095   -1.81096181 -0.14084529]
 [ 0.70448106  1.36237655  0.72071794 -0.18799024]]

Weights2 : 

 [[-0.1491021   0.08685661 -0.11514357]
 [-0.61848288 -0.73816178 -0.26882781]
 [ 0.96565578  0.21554287 -0.43528517]]

Weights3 : 

 [[-1.05726517  1.49887143  0.25812449]]

Bias1: 

  [1.68490619 0.73241281 1.24688067]

Bias2: 

  [-0.05730336 -0.32113283  1.0561405 ]

Bias3: 

  [1.1

**Exercise: Create a dataset using pandas for the following attributes and then predict the housing prices using neural network:
Area: The total area of the house in square feet
Bedrooms: The number of bedrooms in the house.
Bathrooms: The number of bathrooms in the house.
Age: The age of the house in years.
Location: The neighborhood or area where the house is located.
Garage Size: The size of the garage in square feet.
Yard Size: The size of the yard or outdoor space in square feet.
Amenities: A binary feature indicating whether the house has additional amenities such as a swimming pool, gym, etc.
School Rating: The rating of nearby schools, on a scale from 1 to 10.
Distance to City Center: The distance of the house from the city center in miles.
Price: The selling price of the house.**

In [8]:
import numpy
import pandas
data={
    'Area':[2000, 1800, 2500, 2200, 1900, 2800, 2100, 1700, 2400, 2000],
    'Bedrooms':[3, 2, 4, 3, 2, 5, 4, 2, 3, 3],
    'Bathrooms':[2, 1.5, 3, 2.5, 2, 3.5, 2.5, 1, 3, 2],
    'Age':[10, 5, 15, 8, 3, 20, 12, 6, 18, 9],
    'Location':['Suburban', 'Urban', 'Rural', 'Suburban', 'Urban', 'Rural', 'Suburban', 'Urban', 'Rural', 'Suburban'],
    'Garage Size':[400, 300, 500, 450, 350, 600, 400, 250, 550, 400],
    'Yard Size':[800, 600, 1000, 900, 700, 1200, 800, 500, 1100, 800],
    'Amenities':[1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
    'School Rating':[8, 7, 6, 9, 8, 5, 7, 6, 4, 8],
    'Distance to City Center':[5, 2, 10, 7, 4, 15, 6, 3, 12, 5],
    'Price':[300000, 250000, 350000, 320000, 280000, 400000, 310000, 240000, 370000, 300000]
}
df=pandas.DataFrame(data)
df
    
      

Area  Bedrooms  Bathrooms  Age  Location  Garage Size  Yard Size  \
0  2000         3        2.0   10  Suburban          400        800   
1  1800         2        1.5    5     Urban          300        600   
2  2500         4        3.0   15     Rural          500       1000   
3  2200         3        2.5    8  Suburban          450        900   
4  1900         2        2.0    3     Urban          350        700   
5  2800         5        3.5   20     Rural          600       1200   
6  2100         4        2.5   12  Suburban          400        800   
7  1700         2        1.0    6     Urban          250        500   
8  2400         3        3.0   18     Rural          550       1100   
9  2000         3        2.0    9  Suburban          400        800   

   Amenities  School Rating  Distance to City Center   Price  
0          1              8                        5  300000  
1          0              7                        2  250000  
2          1              6                       10  350000  
3          1              9                        7  320000  
4          0              8                        4  280000  
5          1              5                       15  400000  
6          1              7                        6  310000  
7          0              6                        3  240000  
8          1              4                       12  370000  
9          1              8                        5  300000

In [9]:
df.head(5)

Area  Bedrooms  Bathrooms  Age  Location  Garage Size  Yard Size  \
0  2000         3        2.0   10  Suburban          400        800   
1  1800         2        1.5    5     Urban          300        600   
2  2500         4        3.0   15     Rural          500       1000   
3  2200         3        2.5    8  Suburban          450        900   
4  1900         2        2.0    3     Urban          350        700   

   Amenities  School Rating  Distance to City Center   Price  
0          1              8                        5  300000  
1          0              7                        2  250000  
2          1              6                       10  350000  
3          1              9                        7  320000  
4          0              8                        4  280000

In [10]:
dataset=df.values

In [11]:
dataset

array([[2000, 3, 2.0, 10, 'Suburban', 400, 800, 1, 8, 5, 300000],
       [1800, 2, 1.5, 5, 'Urban', 300, 600, 0, 7, 2, 250000],
       [2500, 4, 3.0, 15, 'Rural', 500, 1000, 1, 6, 10, 350000],
       [2200, 3, 2.5, 8, 'Suburban', 450, 900, 1, 9, 7, 320000],
       [1900, 2, 2.0, 3, 'Urban', 350, 700, 0, 8, 4, 280000],
       [2800, 5, 3.5, 20, 'Rural', 600, 1200, 1, 5, 15, 400000],
       [2100, 4, 2.5, 12, 'Suburban', 400, 800, 1, 7, 6, 310000],
       [1700, 2, 1.0, 6, 'Urban', 250, 500, 0, 6, 3, 240000],
       [2400, 3, 3.0, 18, 'Rural', 550, 1100, 1, 4, 12, 370000],
       [2000, 3, 2.0, 9, 'Suburban', 400, 800, 1, 8, 5, 300000]],
      dtype=object)

In [12]:
X = dataset[:,0:10]

In [13]:
Y = dataset[:,10]

In [14]:
from sklearn import preprocessing

In [17]:
import pandas as pd

In [19]:
df = pd.read_csv('housepricedata.csv')
df

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0                3             8           0         548                 1  
1                3             6           1         460                 1  
2                3             6           1         608                 1  
3                3             7           1         642                 0  
4                4             9           1         836                 1  
...            ...           ...         ...         ...               ...  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0  

[1460 rows x 11 columns]

In [20]:
dataset = df.values

In [21]:
dataset

array([[ 8450,     7,     5, ...,     0,   548,     1],
       [ 9600,     6,     8, ...,     1,   460,     1],
       [11250,     7,     5, ...,     1,   608,     1],
       ...,
       [ 9042,     7,     9, ...,     2,   252,     1],
       [ 9717,     5,     6, ...,     0,   240,     0],
       [ 9937,     5,     6, ...,     0,   276,     0]], dtype=int64)

In [22]:
X = dataset[:,0:10]

In [23]:
Y = dataset[:,10]

In [24]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [25]:
X_scale

array([[0.0334198 , 0.66666667, 0.5       , ..., 0.5       , 0.        ,
        0.3864598 ],
       [0.03879502, 0.55555556, 0.875     , ..., 0.33333333, 0.33333333,
        0.32440056],
       [0.04650728, 0.66666667, 0.5       , ..., 0.33333333, 0.33333333,
        0.42877292],
       ...,
       [0.03618687, 0.66666667, 1.        , ..., 0.58333333, 0.66666667,
        0.17771509],
       [0.03934189, 0.44444444, 0.625     , ..., 0.25      , 0.        ,
        0.16925247],
       [0.04037019, 0.44444444, 0.625     , ..., 0.33333333, 0.        ,
        0.19464034]])

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3)

In [28]:
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)

In [29]:
print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)

(1022, 10) (219, 10) (219, 10) (1022,) (219,) (219,)


In [1]:
import numpy as np

# Use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Creating loss function
def loss(predicted, actual):
    return np.mean((predicted - actual) ** 2)

# Define the neural network architecture
input_size = 2
hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# final_output
final_output=None

# Create some variables to track the best loss and the associated weights and biases
best_loss = float('inf')#initially zero
best_W1 = None
best_b1 = None
best_W2 = None
best_b2 = None

for iteration in range(150):
    # Forward pass
    hidden_layer_output = np.dot(x, W1) + b1
    output = sigmoid(np.dot(hidden_layer_output, W2) + b2)

    # save final output
    final_output=output

    # Loss calculation
    current_loss = loss(output, target)

    if current_loss < best_loss:
        print('New weights found, iteration:', iteration, 'loss:', current_loss)
        # Save current weights and biases as the best ones so far
        best_loss = current_loss
        best_W1 = W1.copy()
        best_b1 = b1.copy()
        best_W2 = W2.copy()
        best_b2 = b2.copy()
    else:
        # Revert weights and biases to the previous best values
        W1 = best_W1.copy()
        b1 = best_b1.copy()
        W2 = best_W2.copy()
        b2 = best_b2.copy()

    # Update weights with small random values
    W1 += 0.09 * np.random.randn(input_size, hidden_size)
    b1 += 0.09 * np.random.randn(hidden_size)
    W2 += 0.09 * np.random.randn(hidden_size, output_size)
    b2 += 0.09 * np.random.randn(output_size)

print(final_output)

New weights found, iteration: 0 loss: 0.17975749783268022
New weights found, iteration: 1 loss: 0.1482529143940371
New weights found, iteration: 2 loss: 0.1310379070940262
New weights found, iteration: 3 loss: 0.1254916216384162
New weights found, iteration: 4 loss: 0.1127959004497159
New weights found, iteration: 7 loss: 0.09947259438111225
New weights found, iteration: 11 loss: 0.09113513937864623
New weights found, iteration: 13 loss: 0.08380984500279856
New weights found, iteration: 14 loss: 0.07485265948950344
New weights found, iteration: 15 loss: 0.0744217397393336
New weights found, iteration: 18 loss: 0.07241928941971147
New weights found, iteration: 25 loss: 0.06591645542410444
New weights found, iteration: 28 loss: 0.0520628438958379
New weights found, iteration: 30 loss: 0.04724992237902982
New weights found, iteration: 35 loss: 0.04152636821206253
New weights found, iteration: 36 loss: 0.0367507705539059
New weights found, iteration: 40 loss: 0.035821297080322
New weights 

In [2]:
# Solve the and gate problem and then calculate the loss uisng mean square error.
# run several times of the code and compare the error. Is the result same in every case? If so, why?


import numpy as np

# use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the neural network architecture
input_size = 2
hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# Forward pass
hidden_layer_output = (np.dot(x, W1) + b1)
output = sigmoid(np.dot(hidden_layer_output, W2) + b2)

# Calculate the loss (using Mean Squared Error)
loss = np.mean((output - target) ** 2)

print("Output:")
print(output)
print("Loss:", loss)

Output:
[[0.89013246]
 [0.81529945]
 [0.95064447]
 [0.91299899]]
Loss: 0.5920857668994902


In [3]:
# Solve the and gate problem and then calculate the loss uisng mean square error.
# run several times of the code and compare the error. Is the result same in every case? If so, why?


import numpy as np

# use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the neural network architecture
input_size = 2
hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# Forward pass
hidden_layer_output = (np.dot(x, W1) + b1)
output = sigmoid(np.dot(hidden_layer_output, W2) + b2)

# Calculate the loss (using Mean Squared Error)
loss = np.mean((output - target) ** 2)

print("Output:")
print(output)
print("Loss:", loss)


Output:
[[0.49543945]
 [0.98975634]
 [0.84499765]
 [0.99813929]]
Loss: 0.4847755843369881


In [4]:
import numpy as np

# Use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Creating loss function
def loss(predicted, actual):
    return np.mean((predicted - actual) ** 2)

# Define the neural network architecture
input_size = 2
#hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, output_size)
b1 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# final_output
final_output=None

# Create some variables to track the best loss and the associated weights and biases
best_loss = float('inf')
best_W1 = None
best_b1 = None
best_W2 = None
best_b2 = None

iteration=0

while(best_loss>=0.05):
    # Forward pass
    hidden_layer_output = np.dot(x, W1) + b1
    output = sigmoid(np.dot(hidden_layer_output, W2) + b2)

    # save final output
    final_output=output

    # Loss calculation
    current_loss = loss(output, target)

    iteration=iteration+1

    if current_loss < best_loss:
        print('New weights found, iteration:', iteration, 'loss:', current_loss)
        # Save current weights and biases as the best ones so far
        best_loss = current_loss
        best_W1 = W1.copy()
        best_b1 = b1.copy()
        best_W2 = W2.copy()
        best_b2 = b2.copy()
    else:
        # Revert weights and biases to the previous best values
        W1 = best_W1.copy()
        b1 = best_b1.copy()
        W2 = best_W2.copy()
        b2 = best_b2.copy()

    # Update weights with small random values
    W1 += 0.09 * np.random.randn(input_size, hidden_size)
    b1 += 0.09 * np.random.randn(hidden_size)
    W2 += 0.09 * np.random.randn(hidden_size, output_size)
    b2 += 0.09 * np.random.randn(output_size)

print(final_output)

ValueError: shapes (4,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [ ]:
#import numpy as np

# Use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Creating loss function
def loss(predicted, actual):
    return np.mean((predicted - actual) ** 2)

# Define the neural network architecture
input_size = 2
#hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, output_size)
b1 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# final_output
final_output=None

# Create some variables to track the best loss and the associated weights and biases
best_loss = float('inf')
best_W1 = None
best_b1 = None
best_W2 = None
best_b2 = None

iteration=0

while(best_loss>=0.05):
    # Forward pass
    output = np.dot(x, W1) + b1
    
    # save final output
    final_output=output

    # Loss calculation
    current_loss = loss(output, target)

    iteration=iteration+1

    if current_loss < best_loss:
        print('New weights found, iteration:', iteration, 'loss:', current_loss)
        # Save current weights and biases as the best ones so far
        best_loss = current_loss
        best_W1 = W1.copy()
        best_b1 = b1.copy()
        best_W2 = W2.copy()
        best_b2 = b2.copy()
    else:
        # Revert weights and biases to the previous best values
        W1 = best_W1.copy()
        b1 = best_b1.copy()
        W2 = best_W2.copy()
        b2 = best_b2.copy()

    # Update weights with small random values
    W1 += 0.09 * np.random.randn(input_size, output_size)
    b1 += 0.09 * np.random.randn(output_size)
print(final_output)



In [ ]:
#import numpy as np

# Use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Creating loss function
def loss(predicted, actual):
    return np.mean((predicted - actual) ** 2)

# Define the neural network architecture
input_size = 2
#hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, output_size)
b1 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# final_output
final_output=None

# Create some variables to track the best loss and the associated weights and biases
best_loss = float('inf')
best_W1 = None
best_b1 = None
best_W2 = None
best_b2 = None

iteration=0

while(best_loss>=0.05):
    # Forward pass
    output = np.dot(x, W1) + b1
    
    # save final output
    final_output=output

    # Loss calculation
    current_loss = loss(output, target)

    iteration=iteration+1

    if current_loss < best_loss:
        print('New weights found, iteration:', iteration, 'loss:', current_loss)
        # Save current weights and biases as the best ones so far
        best_loss = current_loss
        best_W1 = W1.copy()
        best_b1 = b1.copy()
        best_W2 = W2.copy()
        best_b2 = b2.copy()
    else:
        # Revert weights and biases to the previous best values
        W1 = best_W1.copy()
        b1 = best_b1.copy()
        W2 = best_W2.copy()
        b2 = best_b2.copy()

    # Update weights with small random values
    W1 += 0.09 * np.random.randn(input_size, output_size)
    b1 += 0.09 * np.random.randn(output_size)
print(final_output)



In [ ]:
#import numpy as np

# Use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Creating loss function
def loss(predicted, actual):
    return np.mean((predicted - actual) ** 2)

# Define the neural network architecture
input_size = 2
#hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, output_size)
b1 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# final_output
final_output=None

# Create some variables to track the best loss and the associated weights and biases
best_loss = float('inf')
best_W1 = None
best_b1 = None
best_W2 = None
best_b2 = None

iteration=0

while(best_loss>=0.05):
    # Forward pass
    output = np.dot(x, W1) + b1
    
    # save final output
    final_output=output

    # Loss calculation
    current_loss = loss(output, target)

    iteration=iteration+1

    if current_loss < best_loss:
        print('New weights found, iteration:', iteration, 'loss:', current_loss)
        # Save current weights and biases as the best ones so far
        best_loss = current_loss
        best_W1 = W1.copy()
        best_b1 = b1.copy()
        best_W2 = W2.copy()
        best_b2 = b2.copy()
    else:
        # Revert weights and biases to the previous best values
        W1 = best_W1.copy()
        b1 = best_b1.copy()
        W2 = best_W2.copy()
        b2 = best_b2.copy()

    # Update weights with small random values
    W1 += 0.09 * np.random.randn(input_size, output_size)
    b1 += 0.09 * np.random.randn(output_size)
print(final_output)

