In [28]:
import numpy as np

# Use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Creating loss function
def loss(predicted, actual):
    return np.mean((predicted - actual) ** 2)

# Define the neural network architecture
input_size = 2
#hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, output_size)
b1 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# final_output
final_output=None

# Create some variables to track the best loss and the associated weights and biases
best_loss = float('inf')
best_W1 = None
best_b1 = None

iteration=0

while(best_loss>=0.05):
    # Forward pass
    layer_output = np.dot(x, W1) + b1
    output = sigmoid(np.dot(x, W1) + b1)

    # save final output
    final_output=output

    # Loss calculation
    current_loss = loss(output, target)

    iteration=iteration+1

    if current_loss < best_loss:
        print('New weights found, iteration:', iteration, 'loss:', current_loss)
        # Save current weights and biases as the best ones so far
        best_loss = current_loss
        best_W1 = W1.copy()
        best_b1 = b1.copy()

    else:
        # Revert weights and biases to the previous best values
        W1 = best_W1.copy()
        b1 = best_b1.copy()
     

    # Update weights with small random values
    W1 += 0.09 * np.random.randn(input_size, output_size)
    b1 += 0.09 * np.random.randn(output_size)
 

print(final_output)

New weights found, iteration: 1 loss: 0.25617202483165047
New weights found, iteration: 3 loss: 0.25158220991812974
New weights found, iteration: 4 loss: 0.23235290879530385
New weights found, iteration: 7 loss: 0.21825358151814928
New weights found, iteration: 8 loss: 0.2070069697995982
New weights found, iteration: 9 loss: 0.20700594759568494
New weights found, iteration: 10 loss: 0.20159791547540779
New weights found, iteration: 11 loss: 0.18782455240835585
New weights found, iteration: 12 loss: 0.1857059654146867
New weights found, iteration: 13 loss: 0.18428773122142217
New weights found, iteration: 14 loss: 0.17756322066715868
New weights found, iteration: 18 loss: 0.17100796337520288
New weights found, iteration: 20 loss: 0.1668491273113996
New weights found, iteration: 22 loss: 0.1638830224490061
New weights found, iteration: 24 loss: 0.14817234033866988
New weights found, iteration: 25 loss: 0.1471414576746687
New weights found, iteration: 27 loss: 0.13968162674087456
New weig

In [9]:
# Solve the and gate problem and then calculate the loss uisng mean square error.
# run several times of the code and compare the error. Is the result same in every case? If so, why?


import numpy as np

# use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the neural network architecture
input_size = 2
hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn( hidden_size,input_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(output_size, hidden_size)
b2 = np.random.randn(output_size)

print(W1)
print(W2)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# Forward pass
hidden_layer_output = (np.dot(x, np.array(W1).T) + b1)
output = sigmoid(np.dot(hidden_layer_output, np.array(W2).T )+ b2)

# Calculate the loss (using Mean Squared Error)
loss = np.mean((output - target) ** 2)

print("Output:")
print(output)
print("Loss:", loss)

[[ 1.47739291  0.13368134]
 [ 0.50032916 -1.60510581]
 [ 0.46640247 -0.35323718]]
[[ 0.76003445 -1.2980962  -1.74882876]]
Output:
[[0.94751777]
 [0.99665289]
 [0.92764786]
 [0.99529326]]
Loss: 0.6879149097954227


In [11]:
import numpy as np

# Use sigmoidal activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Creating loss function
def loss(predicted, actual):
    return np.mean((predicted - actual) ** 2)

# Define the neural network architecture
input_size = 2
hidden_size = 3
output_size = 1

# Initialize the weights and biases
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

# Define the input for the AND gate
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define the target output for the AND gate
target = np.array([[0], [0], [0], [1]])

# final_output
final_output=None

# Create some variables to track the best loss and the associated weights and biases
best_loss = float('inf')
print(f"best loss is:{best_loss}")
best_W1 = None
best_b1 = None
best_W2 = None
best_b2 = None

for iteration in range(150):
    # Forward pass
    hidden_layer_output = np.dot(x, W1) + b1
    output = sigmoid(np.dot(hidden_layer_output, W2) + b2)

    # save final output
    final_output=output

    # Loss calculation
    current_loss = loss(output, target)

    if current_loss < best_loss:
        print('New weights found, iteration:', iteration, 'loss:', current_loss)
        # Save current weights and biases as the best ones so far
        best_loss = current_loss
        best_W1 = W1.copy()
        best_b1 = b1.copy()
        best_W2 = W2.copy()
        best_b2 = b2.copy()
    else:
        # Revert weights and biases to the previous best values
        W1 = best_W1.copy()
        b1 = best_b1.copy()
        W2 = best_W2.copy()
        b2 = best_b2.copy()

    # Update weights with small random values
    W1 += 0.09 * np.random.randn(input_size, hidden_size)
    b1 += 0.09 * np.random.randn(hidden_size)
    W2 += 0.09 * np.random.randn(hidden_size, output_size)
    b2 += 0.09 * np.random.randn(output_size)

print(final_output)

best loss is:inf
New weights found, iteration: 0 loss: 0.5424947577588415
New weights found, iteration: 2 loss: 0.5407614086890614
New weights found, iteration: 4 loss: 0.5201242900805575
New weights found, iteration: 6 loss: 0.49066043574247903
New weights found, iteration: 9 loss: 0.47286484247241073
New weights found, iteration: 10 loss: 0.4503378066710195
New weights found, iteration: 11 loss: 0.4381496935833472
New weights found, iteration: 12 loss: 0.4219054821168376
New weights found, iteration: 16 loss: 0.3912891549865602
New weights found, iteration: 18 loss: 0.34873381372260126
New weights found, iteration: 19 loss: 0.3285630843517353
New weights found, iteration: 20 loss: 0.31852089061888705
New weights found, iteration: 21 loss: 0.31347790769656175
New weights found, iteration: 22 loss: 0.3014129451671213
New weights found, iteration: 24 loss: 0.2839478785152941
New weights found, iteration: 26 loss: 0.23946005179394353
New weights found, iteration: 27 loss: 0.2369549420676

In [19]:
import numpy as np
#loss=1/2*(y'-y)^2
#loss_derivative=y'-y
#sigmoid_derivative=y'*(1-y')
#backpropagation=(y'-y)*y'*(1-y')
#back_propagation=loss_derivative*sigmoid_derivative

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid activation function
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Define the input data and labels for the AND gate problem
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [0], [0], [1]])

# Initialize the weights and biases with random values
#np.random.seed(42)
W = np.random.randn(2, 1)
b = np.random.randn(1)

# Set the learning rate and number of epochs
learning_rate = 0.8
num_epochs = 500

# Training loop
for epoch in range(num_epochs):
    # Forward pass
    z = np.dot(X, W) + b
    a = sigmoid(z)

    # Compute the loss
    loss = np.mean((y - a) ** 2)

    error= (y - a)
    # Backpropagation
    delta = error * sigmoid_derivative(z)
    dW = np.dot(X.T, delta)
    db = np.sum(delta)

    # Update the weights and biases
    W -= learning_rate * dW
    b -= learning_rate * db

    # Print the loss at every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}: Loss = {loss}")

# Test the model on the input data
#predictions = (a >= 0.5).astype(int)
print("Predicted Output:")
print(a)

Epoch 100: Loss = 0.7009254593641837
Epoch 200: Loss = 0.7303958074967896
Epoch 300: Loss = 0.7378318044761677
Epoch 400: Loss = 0.7411948536291323
Epoch 500: Loss = 0.7431073338026416
Predicted Output:
[[0.99675121]
 [0.00863753]
 [0.99487176]
 [0.00547905]]


In [25]:
import numpy as np
#AND operation

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid activation function
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Define the input data and labels for the AND gate problem
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [0], [0], [1]])

# Initialize the weights and biases with random values
np.random.seed(42)
W = np.random.randn(2, 1)
b = np.random.randn(1)

# Set the learning rate and number of epochs
learning_rate = 0.8
num_epochs = 500

# Training loop
for epoch in range(num_epochs):
    # Forward pass
    z = np.dot(X, W) + b
    a = sigmoid(z)

    # Compute the loss
    loss = np.mean((y - a) ** 2)

    error= (y - a)
    # Backpropagation
    delta = error * sigmoid_derivative(z)
    dW = np.dot(X.T, delta)
    db = np.sum(delta)

    # Update the weights and biases
    W -= learning_rate * dW
    b -= learning_rate * db

    # Print the loss at every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}: Loss = {loss}")

# Test the model on the input data
#predictions = (a >= 0.5).astype(int)
print("Predicted Output:")
print(a)

Epoch 100: Loss = 0.743998459915124
Epoch 200: Loss = 0.7470214794177472
Epoch 300: Loss = 0.7480165507492393
Epoch 400: Loss = 0.748512245347843
Epoch 500: Loss = 0.7488092427954165
Predicted Output:
[[0.99836331]
 [0.99958641]
 [0.99966728]
 [0.999916  ]]


In [24]:
import numpy as np
#OR operation

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid activation function
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Define the input data and labels for the AND gate problem
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [1]])

# Initialize the weights and biases with random values
np.random.seed(42)
W = np.random.randn(2, 1)
b = np.random.randn(1)

# Set the learning rate and number of epochs
learning_rate = 0.8
num_epochs = 500

# Training loop
for epoch in range(num_epochs):
    # Forward pass
    z = np.dot(X, W) + b
    a = sigmoid(z)

    # Compute the loss
    loss = np.mean((y - a) ** 2)

    error= (y - a)
    # Backpropagation
    delta = error * sigmoid_derivative(z)
    dW = np.dot(X.T, delta)
    db = np.sum(delta)

    # Update the weights and biases
    W -= learning_rate * dW
    b -= learning_rate * db

    # Print the loss at every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}: Loss = {loss}")

# Test the model on the input data
#predictions = (a >= 0.5).astype(int)
print("Predicted Output:")
print(a)

Epoch 100: Loss = 0.7457842503821006
Epoch 200: Loss = 0.7482270406384637
Epoch 300: Loss = 0.7494896574546598
Epoch 400: Loss = 0.7547234452105485
Epoch 500: Loss = 0.9260643111014422
Predicted Output:
[[9.09171186e-01]
 [3.07676177e-02]
 [3.12594655e-02]
 [1.02323072e-04]]


In [29]:
import numpy as np
#NOR operation

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid activation function
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Define the input data and labels for the AND gate problem
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [1]])

# Initialize the weights and biases with random values
np.random.seed(42)
W = np.random.randn(2, 1)
b = np.random.randn(1)

# Set the learning rate and number of epochs
learning_rate = 0.8
num_epochs = 500

# Training loop
for epoch in range(num_epochs):
    # Forward pass
    z = np.dot(X, W) + b
    a = sigmoid(z)

    # Compute the loss
    loss = np.mean((y - a) ** 2)

    error= (y - a)
    # Backpropagation
    delta = error * sigmoid_derivative(z)
    dW = np.dot(X.T, delta)
    db = np.sum(delta)

    # Update the weights and biases
    W -= learning_rate * dW
    b -= learning_rate * db

    # Print the loss at every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}: Loss = {loss}")

# Test the model on the input data
#predictions = (a >= 0.5).astype(int)
print("Predicted Output:")
print(a)

Epoch 100: Loss = 0.7457842503821006
Epoch 200: Loss = 0.7482270406384637
Epoch 300: Loss = 0.7494896574546598
Epoch 400: Loss = 0.7547234452105485
Epoch 500: Loss = 0.9260643111014422
Predicted Output:
[[9.09171186e-01]
 [3.07676177e-02]
 [3.12594655e-02]
 [1.02323072e-04]]


In [31]:
import numpy as np
#AND operation

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid activation function
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Define the input data and labels for the AND gate problem
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[1], [1], [1], [0]])

# Initialize the weights and biases with random values
np.random.seed(42)
W = np.random.randn(2, 1)
b = np.random.randn(1)

# Set the learning rate and number of epochs
learning_rate = 0.8
num_epochs = 500

# Training loop
for epoch in range(num_epochs):
    # Forward pass
    z = np.dot(X, W) + b
    a = sigmoid(z)

    # Compute the loss
    loss = np.mean((y - a) ** 2)

    error= (y - a)
    # Backpropagation
    delta = error * sigmoid_derivative(z)
    dW = np.dot(X.T, delta)
    db = np.sum(delta)

    # Update the weights and biases
    W -= learning_rate * dW
    b -= learning_rate * db

    # Print the loss at every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}: Loss = {loss}")

# Test the model on the input data
#predictions = (a >= 0.5).astype(int)
print("Predicted Output:")
print(a)

Epoch 100: Loss = 0.7432836555297341
Epoch 200: Loss = 0.7470809107772447
Epoch 300: Loss = 0.7481218311762403
Epoch 400: Loss = 0.7486111980890843
Epoch 500: Loss = 0.7488963664946978
Predicted Output:
[[0.00097506]
 [0.00051197]
 [0.00072118]
 [0.00037862]]


In [41]:
#For X-OR
#Description:https://www.geeksforgeeks.org/backpropagation-in-neural-network/
#Two layer concept:https://towardsdatascience.com/implementing-the-xor-gate-using-backpropagation-in-neural-networks-c1f255b4f20d
import numpy as np 


class NeuralNetwork: 
	def __init__(self, input_size, hidden_size, output_size): 
		self.input_size = input_size 
		self.hidden_size = hidden_size 
		self.output_size = output_size 

		# Initialize weights 
		self.weights_input_hidden = np.random.randn(self.input_size, self.hidden_size) 
		self.weights_hidden_output = np.random.randn(self.hidden_size, self.output_size) 

		# Initialize the biases 
		self.bias_hidden = np.zeros((1, self.hidden_size)) 
		self.bias_output = np.zeros((1, self.output_size)) 

	def sigmoid(self, x): 
		return 1 / (1 + np.exp(-x)) 

	def sigmoid_derivative(self, x): 
		return x * (1 - x) 

	def feedforward(self, X): 
		# Input to hidden 
		self.hidden_activation = np.dot(X, self.weights_input_hidden) + self.bias_hidden 
		self.hidden_output = self.sigmoid(self.hidden_activation) 

		# Hidden to output 
		self.output_activation = np.dot(self.hidden_output, self.weights_hidden_output) + self.bias_output 
		self.predicted_output = self.sigmoid(self.output_activation) 

		return self.predicted_output 

	def backward(self, X, y, learning_rate): 
		# Compute the output layer error 
		output_error = y - self.predicted_output 
		output_delta = output_error * self.sigmoid_derivative(self.predicted_output) 

		# Compute the hidden layer error 
		hidden_error = np.dot(output_delta, self.weights_hidden_output.T) 
		hidden_delta = hidden_error * self.sigmoid_derivative(self.hidden_output) 

		# Update weights and biases 
		self.weights_hidden_output += np.dot(self.hidden_output.T, output_delta) * learning_rate 
		self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate 
		self.weights_input_hidden += np.dot(X.T, hidden_delta) * learning_rate 
		self.bias_hidden += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate 

	def train(self, X, y, epochs, learning_rate): 
		for epoch in range(epochs): 
			output = self.feedforward(X) 
			self.backward(X, y, learning_rate) 
			if epoch % 4000 == 0: 
				loss = np.mean(np.square(y - output)) 
				print(f"Epoch {epoch}, Loss:{loss}") 

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) 
y = np.array([[0], [1], [1], [0]]) 

nn = NeuralNetwork(input_size=2, hidden_size=4, output_size=1) 
nn.train(X, y, epochs=10000, learning_rate=0.1) 

# Test the trained model 
output = nn.feedforward(X) 
print("Predictions after training:") 
print(output) 


Epoch 0, Loss:0.2709390289950311
Epoch 4000, Loss:0.016653247525513573
Epoch 8000, Loss:0.0030754596275636937
Predictions after training:
[[0.03896154]
 [0.95268248]
 [0.95257076]
 [0.0491688 ]]


In [34]:
#For AND gate
import numpy as np 


class NeuralNetwork: 
	def __init__(self, input_size, output_size): 
		self.input_size = input_size  
		self.output_size = output_size 

		# Initialize weights 
		self.weights_input = np.random.randn(self.input_size, self.output_size) 
		# Initialize the biases 
		self.bias_output = np.zeros((1, self.output_size)) 

	def sigmoid(self, x): 
		return 1 / (1 + np.exp(-x)) 

	def sigmoid_derivative(self, x): 
		return x * (1 - x) 

	def feedforward(self, X): 
		 
		self.output_activation = np.dot(X, self.weights_input) + self.bias_output
		self.predicted_output = self.sigmoid(self.output_activation) 

		return self.predicted_output 

	def backward(self, X, y, learning_rate): 
		# Compute the output layer error 
		output_error = y - self.predicted_output 
		output_delta = output_error * self.sigmoid_derivative(self.predicted_output) 

		# Update weights and biases 
		self.weights_input += np.dot(X.T, output_delta) * learning_rate 
		self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate 

	def train(self, X, y, epochs, learning_rate): 
		for epoch in range(epochs): 
			output = self.feedforward(X) 
			self.backward(X, y, learning_rate) 
			if epoch % 4000 == 0: 
				loss = np.mean(np.square(y - output)) 
				print(f"Epoch {epoch}, Loss:{loss}") 

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) 
y = np.array([[0], [0], [0], [1]]) 

nn = NeuralNetwork(input_size=2, output_size=1) 
nn.train(X, y, epochs=10000, learning_rate=0.1) 

# Test the trained model 
output = nn.feedforward(X) 
print("Predictions after training:") 
print(output) 


Epoch 0, Loss:0.27040714284532197
Epoch 4000, Loss:0.007396585537436983
Epoch 8000, Loss:0.0034001372076937933
Predictions after training:
[[2.47775411e-04]
 [5.57563574e-02]
 [5.57563583e-02]
 [9.33637397e-01]]


In [36]:
#For OR gate
import numpy as np 


class NeuralNetwork: 
	def __init__(self, input_size, output_size): 
		self.input_size = input_size  
		self.output_size = output_size 

		# Initialize weights 
		self.weights_input = np.random.randn(self.input_size, self.output_size) 
		# Initialize the biases 
		self.bias_output = np.zeros((1, self.output_size)) 

	def sigmoid(self, x): 
		return 1 / (1 + np.exp(-x)) 

	def sigmoid_derivative(self, x): 
		return x * (1 - x) 

	def feedforward(self, X): 
		 
		self.output_activation = np.dot(X, self.weights_input) + self.bias_output
		self.predicted_output = self.sigmoid(self.output_activation) 

		return self.predicted_output 

	def backward(self, X, y, learning_rate): 
		# Compute the output layer error 
		output_error = y - self.predicted_output 
		output_delta = output_error * self.sigmoid_derivative(self.predicted_output) 

		# Update weights and biases 
		self.weights_input += np.dot(X.T, output_delta) * learning_rate 
		self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate 

	def train(self, X, y, epochs, learning_rate): 
		for epoch in range(epochs): 
			output = self.feedforward(X) 
			self.backward(X, y, learning_rate) 
			if epoch % 4000 == 0: 
				loss = np.mean(np.square(y - output)) 
				print(f"Epoch {epoch}, Loss:{loss}") 

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) 
y = np.array([[0], [1], [1], [1]]) 

nn = NeuralNetwork(input_size=2, output_size=1) 
nn.train(X, y, epochs=10000, learning_rate=0.1) 

# Test the trained model 
output = nn.feedforward(X) 
print("Predictions after training:") 
print(output) 

Epoch 0, Loss:0.2709530110636155
Epoch 4000, Loss:0.0037477644806980996
Epoch 8000, Loss:0.0017253244735124774
Predictions after training:
[[0.05508825]
 [0.96559552]
 [0.96559439]
 [0.99992599]]


In [38]:
#For NAND gate
import numpy as np 


class NeuralNetwork: 
	def __init__(self, input_size, output_size): 
		self.input_size = input_size  
		self.output_size = output_size 

		# Initialize weights 
		self.weights_input = np.random.randn(self.input_size, self.output_size) 
		# Initialize the biases 
		self.bias_output = np.zeros((1, self.output_size)) 

	def sigmoid(self, x): 
		return 1 / (1 + np.exp(-x)) 

	def sigmoid_derivative(self, x): 
		return x * (1 - x) 

	def feedforward(self, X): 
		 
		self.output_activation = np.dot(X, self.weights_input) + self.bias_output
		self.predicted_output = self.sigmoid(self.output_activation) 

		return self.predicted_output 

	def backward(self, X, y, learning_rate): 
		# Compute the output layer error 
		output_error = y - self.predicted_output 
		output_delta = output_error * self.sigmoid_derivative(self.predicted_output) 

		# Update weights and biases 
		self.weights_input += np.dot(X.T, output_delta) * learning_rate 
		self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate 

	def train(self, X, y, epochs, learning_rate): 
		for epoch in range(epochs): 
			output = self.feedforward(X) 
			self.backward(X, y, learning_rate) 
			if epoch % 4000 == 0: 
				loss = np.mean(np.square(y - output)) 
				print(f"Epoch {epoch}, Loss:{loss}") 

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) 
y = np.array([[1], [1], [1], [0]]) 

nn = NeuralNetwork(input_size=2, output_size=1) 
nn.train(X, y, epochs=10000, learning_rate=0.1) 

# Test the trained model 
output = nn.feedforward(X) 
print("Predictions after training:") 
print(output) 

Epoch 0, Loss:0.3288112872702391
Epoch 4000, Loss:0.007186952528413257
Epoch 8000, Loss:0.003351964747114018
Predictions after training:
[[0.99975666]
 [0.94455827]
 [0.94455827]
 [0.06598569]]


In [39]:
#For NOR gate
import numpy as np 


class NeuralNetwork: 
	def __init__(self, input_size, output_size): 
		self.input_size = input_size  
		self.output_size = output_size 

		# Initialize weights 
		self.weights_input = np.random.randn(self.input_size, self.output_size) 
		# Initialize the biases 
		self.bias_output = np.zeros((1, self.output_size)) 

	def sigmoid(self, x): 
		return 1 / (1 + np.exp(-x)) 

	def sigmoid_derivative(self, x): 
		return x * (1 - x) 

	def feedforward(self, X): 
		 
		self.output_activation = np.dot(X, self.weights_input) + self.bias_output
		self.predicted_output = self.sigmoid(self.output_activation) 

		return self.predicted_output 

	def backward(self, X, y, learning_rate): 
		# Compute the output layer error 
		output_error = y - self.predicted_output 
		output_delta = output_error * self.sigmoid_derivative(self.predicted_output) 

		# Update weights and biases 
		self.weights_input += np.dot(X.T, output_delta) * learning_rate 
		self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate 

	def train(self, X, y, epochs, learning_rate): 
		for epoch in range(epochs): 
			output = self.feedforward(X) 
			self.backward(X, y, learning_rate) 
			if epoch % 4000 == 0: 
				loss = np.mean(np.square(y - output)) 
				print(f"Epoch {epoch}, Loss:{loss}") 

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) 
y = np.array([[1], [0], [0], [0]]) 

nn = NeuralNetwork(input_size=2, output_size=1) 
nn.train(X, y, epochs=10000, learning_rate=0.1) 

# Test the trained model 
output = nn.feedforward(X) 
print("Predictions after training:") 
print(output) 

Epoch 0, Loss:0.16360239899675677
Epoch 4000, Loss:0.003679168871372489
Epoch 8000, Loss:0.001709857447719372
Predictions after training:
[[9.45109364e-01]
 [3.42796456e-02]
 [3.42869408e-02]
 [7.31897028e-05]]


In [40]:
#X-OR
import numpy as np 
#np.random.seed(0)

def sigmoid (x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

#Input datasets
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[0],[1],[1],[0]])

epochs = 10000
lr = 0.1
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1

#Random weights and bias initialization
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size=(1,outputLayerNeurons))

print("Initial hidden weights: ",end='')
print(*hidden_weights)
print("Initial hidden biases: ",end='')
print(*hidden_bias)
print("Initial output weights: ",end='')
print(*output_weights)
print("Initial output biases: ",end='')
print(*output_bias)


#Training algorithm
for _ in range(epochs):
	#Forward Propagation
	hidden_layer_activation = np.dot(inputs,hidden_weights)
	hidden_layer_activation += hidden_bias
	hidden_layer_output = sigmoid(hidden_layer_activation)

	output_layer_activation = np.dot(hidden_layer_output,output_weights)
	output_layer_activation += output_bias
	predicted_output = sigmoid(output_layer_activation)

	#Backpropagation
	error = expected_output - predicted_output
	d_predicted_output = error * sigmoid_derivative(predicted_output)
	
	error_hidden_layer = d_predicted_output.dot(output_weights.T)
	d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

	#Updating Weights and Biases
	output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
	output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
	hidden_weights += inputs.T.dot(d_hidden_layer) * lr
	hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr

print("Final hidden weights: ",end='')
print(*hidden_weights)
print("Final hidden bias: ",end='')
print(*hidden_bias)
print("Final output weights: ",end='')
print(*output_weights)
print("Final output bias: ",end='')
print(*output_bias)

print("\nOutput from neural network after 10,000 epochs: ",end='')
print(*predicted_output)

Initial hidden weights: [0.06505159 0.94888554] [0.96563203 0.80839735]
Initial hidden biases: [0.30461377 0.09767211]
Initial output weights: [0.68423303] [0.44015249]
Initial output biases: [0.12203823]
Final hidden weights: [3.75165818 5.81708984] [3.76618077 5.8897441 ]
Final hidden bias: [-5.75514663 -2.44767828]
Final output weights: [-8.21922452] [7.58395441]
Final output bias: [-3.42278259]

Output from neural network after 10,000 epochs: [0.05494614] [0.94962653] [0.94940782] [0.05442674]
